/**
 * This code was generated by Builder.io.
 */
import React from "react";

export default function Logo() {
  return (
    <div className="flex gap-2 justify-center items-center text-xl font-medium leading-snug text-white whitespace-nowrap">
      <div className="flex shrink-0 self-stretch my-auto bg-white rounded-full h-[22px] w-[22px]" />
      <div className="self-stretch my-auto">OnlyPipe</div>
    </div>
  );
}
