/**
 * This code was generated by Builder.io.
 */
import React from "react";

type SignUpStepProps = {
  number: number;
  title: string;
  isActive: boolean;
};

export default function SignUpStep({
  number,
  title,
  isActive,
}: SignUpStepProps) {
  const activeClasses = isActive
    ? "bg-white text-black"
    : "bg-white bg-opacity-10 text-white text-opacity-80";

  return (
    <div
      className={`flex overflow-hidden flex-col grow shrink justify-center p-6 rounded-2xl w-[130px] max-md:px-5 ${activeClasses}`}
    >
      <div
        className={`px-2.5 w-6 h-6 text-sm ${
          isActive ? "font-medium" : ""
        } leading-loose text-center text-white whitespace-nowrap ${
          isActive ? "bg-black" : "bg-white bg-opacity-20"
        } rounded-[100px]`}
      >
        {number}
      </div>
      <div
        className={`mt-6 text-base leading-6 ${isActive ? "font-medium" : ""}`}
      >
        {title}
      </div>
    </div>
  );
}
