/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { Button, Input, Label } from "@/components/ui";
import SignUpStep from "./SignUpStep";
import SocialSignUp from "./SocialSignUp";
import Logo from "./Logo";

type SignUpPageProps = {
  steps: Array<{ number: number; title: string; isActive: boolean }>;
};

export default function SignUpPage({ steps }: SignUpPageProps) {
  const [showPassword, setShowPassword] = useState(false);

  return (
    <main className="flex flex-wrap bg-black rounded-none">
      <section className="flex flex-1 shrink gap-2.5 p-3 h-full basis-[168px] min-w-[240px] max-md:max-w-full">
        <div className="flex overflow-hidden flex-col flex-1 shrink items-start p-14 w-full basis-0 min-w-[240px] rounded-[32px] max-md:px-5 max-md:max-w-full">
          <Logo />
          <div className="flex flex-col justify-center max-w-full mt-[580px] w-[505px] max-md:mt-10">
            <div className="flex flex-wrap gap-6 justify-center items-end w-full max-md:max-w-full">
              <h1 className="flex-1 shrink text-4xl font-medium leading-10 text-white basis-0">
                Get Started with Us
              </h1>
              <p className="text-lg leading-7 text-white text-opacity-80 w-[220px]">
                Complete these easy steps to register your account.
              </p>
            </div>
            <div className="flex flex-wrap gap-2 items-start mt-10 w-full max-md:max-w-full">
              {steps.map((step) => (
                <SignUpStep key={step.number} {...step} />
              ))}
            </div>
          </div>
        </div>
      </section>
      <section className="flex overflow-hidden gap-2.5 justify-center items-center px-24 py-36 h-full min-w-[240px] w-[628px] max-md:px-5 max-md:py-24 max-md:max-w-full">
        <div className="flex flex-col flex-1 shrink self-stretch my-auto w-full basis-0 min-w-[240px] max-md:max-w-full">
          <div className="flex flex-col w-full text-center max-md:max-w-full">
            <h2 className="text-3xl font-medium leading-none text-white max-md:max-w-full">
              Sign Up Account
            </h2>
            <p className="mt-2 text-base leading-normal text-white text-opacity-80 max-md:max-w-full">
              Enter your personal data to create your account.
            </p>
          </div>
          <div className="flex flex-col mt-14 w-full text-base leading-normal max-md:mt-10 max-md:max-w-full">
            <SocialSignUp />
            <div className="flex gap-4 items-center mt-8 w-full text-sm leading-none whitespace-nowrap text-white text-opacity-70 max-md:max-w-full">
              <div className="flex-1 shrink self-stretch my-auto h-px border border-solid basis-0 border-white border-opacity-20 w-[194px]" />
              <div className="self-stretch my-auto">Or</div>
              <div className="flex-1 shrink self-stretch my-auto h-px border border-solid basis-0 border-white border-opacity-20 w-[194px]" />
            </div>
            <form className="flex flex-col mt-8 w-full max-md:max-w-full">
              <div className="flex flex-col flex-1 shrink justify-center w-full basis-0 min-w-[240px] max-md:max-w-full">
                <Label htmlFor="email" className="font-medium text-white">
                  Email
                </Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="eg. johnfrans@gmail.com"
                  className="gap-2.5 self-stretch px-5 py-4 mt-2.5 w-full rounded-xl bg-white bg-opacity-10 text-white text-opacity-70 max-md:max-w-full"
                />
              </div>
              <div className="flex flex-col flex-1 shrink justify-center w-full basis-0 min-w-[240px] mt-6 max-md:max-w-full">
                <Label htmlFor="username" className="font-medium text-white">
                  Username
                </Label>
                <Input
                  id="username"
                  type="text"
                  placeholder="eg. john_doe"
                  className="gap-2.5 self-stretch px-5 py-4 mt-2.5 w-full rounded-xl bg-white bg-opacity-10 text-white text-opacity-70 max-md:max-w-full"
                />
              </div>
              <div className="flex flex-col flex-1 shrink justify-center w-full basis-0 min-w-[240px] mt-6 max-md:max-w-full">
                <Label htmlFor="password" className="font-medium text-white">
                  Password
                </Label>
                <div className="flex gap-2.5 items-center px-5 py-4 mt-2.5 w-full rounded-xl bg-white bg-opacity-10 max-md:max-w-full">
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="Enter your password"
                    className="flex-1 shrink self-stretch my-auto basis-0 bg-transparent border-none text-white text-opacity-70"
                  />
                  <button
                    type="button"
                    onClick={() => setShowPassword(!showPassword)}
                    className="focus:outline-none"
                    aria-label={
                      showPassword ? "Hide password" : "Show password"
                    }
                  >
                    <img
                      src={
                        showPassword ? "/icons/eye-off.svg" : "/icons/eye.svg"
                      }
                      alt=""
                      className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
                    />
                  </button>
                </div>
                <p className="mt-2.5 text-white text-opacity-70">
                  Must be at least 8 characters.
                </p>
              </div>
              <Button className="gap-2.5 self-stretch p-4 mt-8 w-full font-semibold text-black bg-white rounded-xl max-md:max-w-full">
                Sign Up
              </Button>
            </form>
            <p className="self-start mt-8 text-center text-white text-opacity-70 max-md:max-w-full">
              Already have an account?{" "}
              <span className="font-semibold text-white">Log in</span>
            </p>
          </div>
        </div>
      </section>
    </main>
  );
}
