/**
 * This code was generated by Builder.io.
 */
import React from "react";

export default function SocialSignUp() {
  return (
    <div className="flex gap-4 items-start w-full font-medium text-white whitespace-nowrap max-md:max-w-full">
      <Button
        variant="outline"
        className="flex flex-1 shrink gap-2 justify-center items-center p-4 rounded-xl border border-solid basis-0 border-white border-opacity-20"
      >
        <img
          src="/icons/google.svg"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
        />
        <span className="self-stretch my-auto">Google</span>
      </Button>
      <Button
        variant="outline"
        className="flex flex-1 shrink gap-2 justify-center items-center p-4 rounded-xl border border-solid basis-0 border-white border-opacity-20"
      >
        <img
          src="/icons/github.svg"
          alt=""
          className="object-contain shrink-0 self-stretch my-auto w-5 aspect-square"
        />
        <span className="self-stretch my-auto">Github</span>
      </Button>
    </div>
  );
}
